/*
CODIGO PARA CREACION DEL SUPER ADMIN DE MIS DB
*/

CREATE USER 'adminAsignaturas'@'%' 
IDENTIFIED BY 'dAH0*_292X-uHFoR';
#IDENTIFIED VIA mysql_native_password 
#USING '***';
GRANT ALL PRIVILEGES ON *.* 
TO 'adminAsignaturas'@'%' 
REQUIRE NONE WITH GRANT 
OPTION MAX_QUERIES_PER_HOUR 0 
MAX_CONNECTIONS_PER_HOUR 0 
MAX_UPDATES_PER_HOUR 0 
MAX_USER_CONNECTIONS 0;

/*
CODIGO PARA CREACION DEL ADMIN DE MIS DB
*/

#adminBasic
#g5Il1Co)mcP[BCng

CREATE USER 'adminBasic'@'%' 
IDENTIFIED BY 'g5Il1Co)mcP[BCng'
#IDENTIFIED VIA mysql_native_password USING '***';
GRANT USAGE ON *.* TO 'adminBasic'@'%' 
REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 
MAX_CONNECTIONS_PER_HOUR 0 
MAX_UPDATES_PER_HOUR 0 
MAX_USER_CONNECTIONS 0;

GRANT ALL PRIVILEGES ON `bdasignaturas`.* 
TO 'adminBasic'@'%' WITH GRANT OPTION; 
GRANT ALL PRIVILEGES ON `login`.* 
TO 'adminBasic'@'%' WITH GRANT OPTION;

/*
CODIGO PARA CREACION DEL ADMIN DE MIS DB
*/

#directorCarrera
#D@(mWBMs8lL([a/6